Better error handling for creation of demo keys
acquia/reservoir pull request #4
Opened 2017-06-19 16:03 UTC by chris-hamper

Displays the failure message if the openssl key creation fails during install, which can happen even if the functions are defined

2017-06-19 16:08 UTC, wimleers requested changes
Minor nits :)

2017-06-19 16:08 UTC, wimleers commented on reservoir.install
> +    return [ NULL, NULL ];
`[ NULL, NULL ]` should be `[NULL, NULL]`

2017-06-19 16:08 UTC, wimleers commented on reservoir.install
> +
Let's remove this blank line, so that it's clear the comment on line 30 also applies to this.

2017-06-23 19:49 UTC, chris-hamper commented
@wimleers fixed!

2017-06-29 16:26 UTC, wimleers approved these changes

2017-06-29 16:26 UTC, merged